### ISSUE TITLE
unable to compile and run in kali linux

### ISSUE THREAD

**Issue by dcliss** [mattwright324/windows-smb-cracker#1]
hi there ,
is it compatible with kali linux.
i tried compiling and runnning it
failed 

please check the pastebin error message thanks
https://pastebin.com/iZCgQSy6

**Comment by mattwright324** [comment]
Hi dcliss, it should be compatible with linux. What version of Java do you have installed? You'll want to install two packages: `sudo apt install default-jre openjfx`. However, you shouldn't need to compile the app. You can download the precompiled jar from the releases section (with dependencies included).
